config/routes.rb
Minicontest::Application.routes.draw do
  root to: 'session#show'
  authpwn_session

  resources :users, only: [:new, :create, :show]
  resources :submissions, only: [:index, :new, :create]
  resources :scores, only: [:index]
  resources :verdicts, only: [:show] do
    member { get :endpoint_response }
  end

  ActiveAdmin.routes(self)
end

app/controllers/session_controller.rb
# Manages logging in and out of the application.
class SessionController < ApplicationController
  include Authpwn::SessionController

  # Sets up the 'session/welcome' view. No user is logged in.
  def welcome
    render action: 'new'
  end
  private :welcome

  # Sets up the 'session/home' view. A user is logged in.
  def home
    @categories = Category.includes(:problems).all
  end
  private :home

  # The notification text displayed when a session authentication fails.
  def bounce_notice_text(reason)
    case reason
    when :invalid
      'Invalid e-mail or password'
    when :expired
      'Password expired. Please click "Forget password"'
    when :blocked
      'Account blocked. Please verify your e-mail address'
    end
  end

  # A user is logged in, based on a token.
  def home_with_token(token)
    respond_to do |format|
      format.html do
        case token
        when Tokens::EmailVerification
          redirect_to session_url, :notice => 'E-mail address confirmed'
        when Tokens::PasswordReset
          redirect_to change_password_session_url
        # Handle other token types here.
        end
      end
      format.json do
        # Rely on default behavior.
      end
    end
  end
  private :home_with_token

  # If true, every successful login results in a SQL query that removes expired
  # session tokens from the database, to keep its size down.
  #
  # For better performance, set this to false and periodically call
  # Tokens::SessionUid.remove_expired in background thread.
  self.auto_purge_sessions = true

  # You shouldn't extend the session controller, so you can benefit from future
  # features. But, if you must, you can do it here.
end

app/views/session/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, required: true, placeholder: 'you@mit.edu',
                      :class => :normal_input %>
  </div>
  <div class="field">
    <%= f.label :team_name %><br />
    <%= f.text_field :team_name, required: true, placeholder: 'Team Awesome',
                     :class => :normal_input %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, required: true, :class => :normal_input %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, required: true,
                         :class => :normal_input %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/session/_login_form.html.erb
<div class="row">
<div class="five columns centered">
<div id="front_logo">
<%= image_tag("front-logo.png"); %>
</div>
<h2>Sign in</h2>

<% if @redirect_url %>
<p>
  We need you to log in before we can show you the page that you are trying to
  view.
</p>
<% end %>

<%= form_tag session_path, id: 'login_form' do %>

  <div class="field">
    <%= label_tag :email, 'Email Address' %><br />
    <span class="value">
      <%= email_field_tag :email, @email, autofocus: true, required: true,
            placeholder: 'you@mit.edu' %>
    </span>
  </div>

  <div class="field">
    <%= label_tag :password %><br />
    <span class="value">
      <%= password_field_tag :password %>
    </span>
  </div>

  <div class="actions">
    <%= button_tag 'Log in', type: 'submit', name: 'login',
          value: 'requested' %>
    <%= button_tag 'Reset Password', type: 'submit', name: 'reset_password',
          value: 'requested', formaction: reset_password_session_path %>

    <% if @redirect_url %>
    <%= hidden_field_tag :redirect_url, @redirect_url %>
    <% end %>
  </div>
<% end %>

<p id="new_users">
  Don't have an account yet?<br />
  <%= link_to 'Click here to register', new_user_path %>.
</p>
</div>
</div>

app/views/session/forbidden.html.erb
<% if current_user %>
<p>
  You are not allowed to see this page.
</p>

<p>
  You are currently logged in as <%= current_user.email %>. Please
  <%= link_to 'log out', session_path, :method => :delete %> and log in as a
  different user.
</p>
<% else %>
<p>
  The page you are trying to see requires that you
  <%= link_to 'log in', new_session_path %>.
</p>
<script type="text/javascript">
window.location = "<%= new_session_path %>";
</script>
<% end %>

app/views/session/home.html.erb
<%= stylesheet_link_tag    "home", :media => "all" %>

<% if current_user.admin %>
<p>
  <a href="/admin">Admin panel</a>
</p>
<% end %>

<% @categories.each do |category| %>
<div class="category">
  <h2><%= category.name %></h2>

  <% category.problems.select { |problem| problem.visible_to? current_user }.
              sort_by!(&:name).each do |problem| %>
  <div class="problem">
    <h3 class="problem-header">
      <%= link_to problem.name, new_submission_path(problem_id: problem) %>
      (<%= problem.weight %> pts)
    </h3>

    <% if problem.submissions.for_user(current_user).empty? %>
      You have not yet attempted to solve this problem.
    <% else %>
      <h4>Submissions</h4>
      <% problem.submissions.for_user(current_user).recent_first.
                 each do |submission| %>
      <div class="solution">
        <span class="time"><%= (submission.created_at + Time.zone_offset('EST')).strftime('%H:%M:%S') %></span> |
        <span class="verdict">
          <% if submission.verdict %>
            <% if submission.verdict.accepted? %>
              Score: <%= link_to submission.score, submission.verdict %>
            <% else %>
              <%= link_to submission.verdict.message, submission.verdict %>
            <% end %>
          <% else %>
            Queued for grading
          <% end %>
        </span>

        <div class="solution-body">
          <%= submission.code %>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
  <% end %>

</div>
<% end %>

app/views/session/new.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag :login %>
  <%= javascript_include_tag :login %>
<% end %>

<div id="actual_registration_page">
  <%= render 'login_form' %>
</div>

app/views/session/password_change.html.erb
<h2>Password Change</h2>

<% if @credential.updated_at %>
<p class="password_age_notice">
  Your have been using the same password for
  <span class="password_age">
    <%= time_ago_in_words @credential.updated_at, true %>.
  </span>
</p>
<% end %>

<%= form_for @credential, :url => change_password_session_path,
                          :as => :credential, :method => :post do |f| %>
  <section class="fields">
  <% unless @credential.new_record? %>
  <div class="field">
    <%= label_tag :old_password, 'Current Password' %><br />
    <span class="value">
      <%= password_field_tag :old_password %>
    </span>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :password, 'New Password' %><br />
    <span class="value">
      <%= f.password_field :password %>
    </span>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, 'Re-enter New Password' %><br />
    <span class="value">
      <%= f.password_field :password_confirmation %>
    </span>
  </div>
  </section>

  <div class="actions">
    <%= f.submit 'Change Password' %>
  </div>
<% end %>